name: Secure Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

jobs:
  security-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety flake8 bandit

      # Install git-secrets
      - name: Install git-secrets
        run: |
          sudo apt-get update
          sudo apt-get install -y git-secrets

      # Authenticate & safety scan
      - name: Authenticate & scan
        uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_TOKEN }}

      # Code linting
      - name: Lint with Flake8
        run: flake8 .

      # Static Application Security Testing (SAST) with Bandit
      - name: Bandit Scan
        run: bandit -r .

      # Secrets check
      - name: Secrets Check
        run: git secrets --scan -r .
